<a href="https://colab.research.google.com/github/MSY1126/BNH/blob/main/%EB%94%B0%EB%8B%A5!!_%EB%8B%A4%EC%A4%91%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.models import Sequential
from keras.layers import MaxPooling2D
from keras.layers import Conv2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np
import os
import numpy as np
import tensorflow as tf
from keras_preprocessing.image import ImageDataGenerator

import matplotlib.pyplot as plt

In [ ]:
#랜덤 노이즈
def add_random_noise(x):
  x = x + np.random.normal(size=x.shape) * np.random.uniform(1, 5)
  x = x - x.min()
  x = x / x.max()
  return x * 255.0

In [ ]:
# 분류 대상 카테고리 선택
accident_dir = "/content/drive/MyDrive/2조/dataset_2"
categories = ["A","B","C","D","E"]
nb_classes = len(categories)

In [ ]:
# Augmentation
training_datagen = ImageDataGenerator(
    rescale= 1./255,
    rotation_range=40,
    width_shift_range= 0.2,
    height_shift_range=0.2,
    shear_range= 0.2,
    zoom_range = 0.2,
    brightness_range = (0.5, 1.3),
    fill_mode = 'nearest',
    preprocessing_function= add_random_noise)

# 테스트는 그대로 
test_datagen = ImageDataGenerator(rescale = 1./255)

In [ ]:
#  이미지 불러오기 & 모델에 넣기
accident_data = "/content/drive/MyDrive/2조/dataset_2"
train_generator = training_datagen.flow_from_directory(
    accident_dir,
    # batch_size = batch_size,  # 한번에 몇 번 읽을거야? 
    target_size = (224, 224),
    class_mode = 'categorical', # 카테고리 별 클래스 
    shuffle = True # 데이터 읽을 때 마다 랜덤하게 읽을거야
)

Found 2148 images belonging to 5 classes.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
# 이미지 크기 지정 
image_w = 64 
image_h = 64
pixels = image_w * image_h * 3

In [ ]:
X = []
Y = []
for idx, cat in enumerate(categories):
    # 레이블 지정 
    label = [0 for i in range(nb_classes)]
    label[idx] = 1
    # 이미지 
    image_dir = accident_dir + "/" + cat
    files = glob.glob(image_dir+"/*.png")
    for i, f in enumerate(files):
        img = Image.open(f) 
        img = img.convert("RGB")
        img = img.resize((image_w, image_h))
        data = np.asarray(img)      # numpy 배열로 변환
        X.append(data)
        Y.append(label)
        if i % 10 == 0:
            print(i, "\n", data)
X = np.array(X)
Y = np.array(Y)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
200 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
210 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[2

In [ ]:
# 학습 전용 데이터와 테스트 전용 데이터 구분 
X_train, X_test, y_train, y_test = \
    train_test_split(X, Y)
xy = (X_train, X_test, y_train, y_test)

print('>>> data 저장중 ...')
np.save("/content/drive/MyDrive/2조/dataset_2", xy)
print("ok,", len(Y))

>>> data 저장중 ...
ok, 2148


/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


In [ ]:
import numpy as np

X_train, X_test, y_train, y_test = np.load('/content/drive/MyDrive/2조/dataset_2.npy', allow_pickle=True)

In [ ]:
# import numpy as np
# from keras.datasets import imdb

# # save np.load
# np_load_old = np.load

# # modify the default parameters of np.load
# np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

# # call load_data with allow_pickle implicitly set to true
# X_train, X_test, y_train, y_test = imdb.load_data(num_words=10000)

# # restore np.load for future normal usage
# np.load = np_load_old

In [ ]:
# 카테고리 지정하기
categories = ["A","B","C","D","E"]
nb_classes = len(categories)
# 이미지 크기 지정하기
image_w = 64
image_h = 64
# # 데이터 열기 
# X_train, X_test, y_train, y_test = np.load("/content/drive/MyDrive/2조/dataset_2.npy")
# 데이터 정규화하기(0~1사이로)
X_train = X_train.astype("float") / 255
X_test  = X_test.astype("float")  / 255
print('X_train shape:', X_train.shape)

X_train shape: (1611, 64, 64, 3)


In [ ]:
# !pip install q tensorflow==2.1

# !pip install q keras==2.3.1

# !pip install imgaug

# !pip install -U segmentation-models

In [ ]:
from keras.models import Sequential
from keras.layers import MaxPooling2D
from keras.layers import Conv2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np
import os

In [ ]:
# 모델 구조 정의 
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=X_train.shape[1:], padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))

model.add(Conv2D(64, (3, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))


In [ ]:
# 전결합층
model.add(Flatten())    # 벡터형태로 reshape
model.add(Dense(512))   # 출력
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(nb_classes))
model.add(Activation('softmax'))

In [ ]:
# 모델 구축하기
model.compile(loss='categorical_crossentropy',   # 최적화 함수 지정
    optimizer='rmsprop',
    metrics=['accuracy'])

In [ ]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 64, 64, 32)        896       
                                                                 
 activation (Activation)     (None, 64, 64, 32)        0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 32, 32, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 32, 32, 32)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 64)        18496     
                                                                 
 activation_1 (Activation)   (None, 32, 32, 64)        0         
                                                        

In [45]:
# 학습 완료된 모델 저장
hdf5_file = "/content/drive/MyDrive/2조/dataset_2/dataset_2-model.hdf5"
if os.path.exists(hdf5_file):
    # 기존에 학습된 모델 불러들이기
    model.load_weights(hdf5_file)
else:
    # 학습한 모델이 없으면 파일로 저장
    model.fit(X_train, y_train, batch_size=32, epochs=50)
    model.save_weights(hdf5_file)

In [52]:
from keras.models import load_model
# 적용해볼 이미지 
test_image = '/content/drive/MyDrive/2조/dataset_2/B/B-TEST.png'
predictions = model.predict(X_test)

17/17 [==============================] - 0s 6ms/step


In [53]:

# 이미지 resize
img = Image.open(test_image)
img = img.convert("RGB")
img = img.resize((64,64))
data = np.asarray(img)
X = np.array(data)
X = X.astype("float") / 256
X = X.reshape(-1, 64, 64,3)
# 예측
pred = model.predict(X)  
result = [np.argmax(value) for value in pred]   # 예측 값중 가장 높은 클래스 반환
print('New data category : ',categories[result[0]])

1/1 [==============================] - 0s 17ms/step
New data category :  B
